# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 01:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('idquiz', models.AutoField(db_column='idQuiz', primary_key=True, serialize=False)),
                ('quiz', models.TextField(db_column='quiz', validators=[django.core.validators.MinLengthValidator(300)])),
                ('option_a', models.CharField(db_column='optionA', max_length=60)),
                ('option_b', models.CharField(db_column='optionB', max_length=60)),
                ('option_c', models.CharField(db_column='optionC', max_length=60)),
                ('option_d', models.CharField(db_column='optionD', max_length=60)),
                ('shareable_key', models.CharField(db_column='shareableKey', max_length=50)),
            ],
            options={
                'verbose_name': 'Quiz',
                'db_table': 'quizzes',
                'managed': True,
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('idvote', models.AutoField(db_column='idVote', primary_key=True, serialize=False)),
                ('option', models.CharField(db_column='option', max_length=60)),
                ('quiz', models.ForeignKey(db_column='quiz', on_delete=django.db.models.deletion.CASCADE, to='votingapp.Quizzes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
