# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='shareable_key',
            field=models.CharField(db_column='shareableKey', max_length=50, unique=True),
        ),
    ]
